FROM srcml/opensuse_x86_64_base:latest

RUN zypper --non-interactive install --no-recommends rpm-build

#CMD ["/bin/bash", "-c", "curl https://github.com/mlcollard.gpg | sed -i -e '$a\' | rpm --import - ;"]

CMD /bin/bash -c "mkdir /srcML-build; \
	curl https://github.com/mlcollard.gpg > key; echo >> key; gpg --import key ; \
	echo 'gpg list keys:'; \
	gpg --list-keys; \
	echo 'end gpg list keys:'; \
	gpg --import /srcML-Package/secret.key; \
	echo 'gpg list secret keys:'; \
	gpg --list-secret-keys; \
	echo 'end gpg list secret keys:'; \
	curl https://github.com/mlcollard.gpg > key; echo >> key; rpm --import key ; \
	echo 'rpm list keys:'; \
	rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'; \
	echo -e '%_signature gpg\n%_gpg_name Michael L. Collard' > ~/.rpmmacros; \
	cat ~/.rpmmacros; "
#	rpm --addsign /srcML-Package/opensuse_latest_x86_64.rpm \
#"

# CMD ["/bin/bash", "-c", \
# 	 "mkdir /srcML-build; \
#       cd /srcML-build; \
#       cmake /srcML -DCMAKE_BUILD_TYPE=Release; \
#       make -j2; \
#       cpack; \
#       cpack -G RPM; \
#       mv dist/srcML*.tar.gz /srcML-Package/opensuse_latest_x86_64.tar.gz; \
#       mv dist/srcML*.rpm /srcML-Package/opensuse_latest_x86_64.rpm; \
#       curl https://github.com/mlcollard.gpg | sed -i -e '$a\' | rpm --import - ;" \
#       ]
